apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: gcp-secrets-manager
spec:
  backendType: gcpSecretsManager
  # Project to use for GCP Secrets Manager (use the service account project by default)
  projectId: kes-to-eso-validation
  data:
      # Key in GCP Secrets Manager (without projet and version)
    - key: test-key
      # Key to use in Kubernetes secret (not the secret name, who is determined by metadata.name)
      name: the-food-i-hate-the-most
      property: fruit
      # If the secret is a valid JSON, try to get this property
      # Version of the secret (default: 'latest')
      # If the secret is already encoded in base64, then sends it unchanged (default: false)
